# Generated by Django 5.0.6 on 2024-11-05 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcategory',
            old_name='category_name',
            new_name='name',
        ),
    ]
