# Generated by Django 5.0.6 on 2024-11-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_rename_category_name_taskcategory_name'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=100)),
                ('task_description', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('task_assign_date', models.DateField(auto_now_add=True)),
                ('categories', models.ManyToManyField(related_name='categories', to='category.taskcategory')),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
